[package]
authors = ["Ockam Developers"]
description = """
"""
edition = "2018"
homepage = "https://www.ockam.io/"
keywords = ["ockam"]
license = "Apache-2.0"
name = "ockam_vault"
readme = "README.md"
repository = "https://github.com/ockam-network/ockam"
version = "0.0.0"

[features]
default = ["std"]

# Requires the Rust Standard Library.
std = []

[dependencies]
ockam_core = {path = "../ockam_core", version = "*"}
ockam_vault_core = {path = "../ockam_vault_core", version = "*"}
arrayref = "0.3"
curve25519-dalek = "3.0"
ed25519-dalek = "1.0"
hkdf = "0.9"
hex = "0.4"
rand = "0.7"
sha2 = "0.9"
x25519-dalek = "1.0"
hashbrown = "0.9.1"
zeroize = { version = "1.1", features = ["zeroize_derive"] }

[dev-dependencies]
hex = "0.4"
