[workspace]

members = [
    "common",
    "daemon",
    "examples",
    "kex/traits",
    "kex/xx",
    "kex/x3dh",
#    "kex/ffi", Doesn't work
    "vault/traits",
    "vault/software",
    "vault/file",
    "vault/ffi",
    "router",
    "queue_topic",
    "transport",
#    "node", Needs to implement new vault api
#    "c/generate_bindings",
    "c/bindings",
    "c/rust_memory",
    "message_router",
    "queue",
    "tcp_router",
    "worker_manager",
    "channel_refactor",
]

exclude = [
    "okta"
]

default-members = [
    "common",
    "daemon",
    "examples",
    "kex/traits",
    "kex/xx",
    "kex/x3dh",
#    "kex/ffi", Doesn't work
    "vault/traits",
    "vault/software",
    "vault/file",
    "vault/ffi",
    "router",
    "queue_topic",
    "transport",
#   "node", Needs to implement new vault api
    "c/bindings",
    "c/rust_memory",
    "message_router",
    "queue",
    "tcp_router",
    "worker_manager",
    "channel_refactor",
]
