[package]
name = "network"
version = "0.0.0"
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["rt-core", "tcp", "sync", "macros", "io-driver", "io-util", "time"] }
executor = "0.7"
